import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { NextAuthProvider } from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import Navbar2 from "./Navbar";
import { ThemeProvider } from "@mui/material/styles";

const inter = Inter({ subsets: ["latin"] });
import theme from "./theme";
export const metadata: Metadata = {
  title: "Tech News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          <div>
            <NextAuthProvider>
              <div> {children}</div>
              <Toaster />
            </NextAuthProvider>
          </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
